[package]
name = "loriini"
version = "0.1.4"
edition = "2021"

[dependencies]
rand = "*"
hex = "*"
termion = "*"
palette = "*"
itertools = "*"
clap = {version = "*", features = ["derive"]}
cli-clipboard = "0.4.0"
