[package]
name = "loriini"
version = "0.1.7"
edition = "2024"
description = "A console color picker"
license = "MIT"
repository = "https://github.com/kolja/loriini"
homepage = "https://github.com/kolja/loriini"
keywords = ["cli", "color", "tui", "picker"]
categories = ["command-line-utilities"]

[dependencies]
rand = "0.10"
hex = "0.4"
termion = "4.0"
palette = "0.7.6"
itertools = "0.14"
clap = {version = "4.5", features = ["derive"]}

