name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose

  release:
    needs: build_and_test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all --verbose

    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.operating-system }}
        path: |
          target/release/loriini
